### ISSUE TITLE
Change of repo name to awesome

### ISSUE THREAD

**Issue by zx8754** [nhs-r-community/awesome-nhsr#5]
These kind of lists are usually called **awesome**, for example see - https://github.com/topics/awesome

So here are some suggestions:
 1. nhsr-awesome
 2. nhs-r-awesome
 3. awesome-nhsr
 4. awesome-nhs-r
 5. other?

**Comment by ChrisBeeley** [comment]
Like it! 

awesome-nhsr gets my vote. @jasonpott what do you think?

**Comment by jasonpott** [comment]
Absolutely - sounds good to me 😎

**Comment by ChrisBeeley** [comment]
Motion carries, thanks both
